version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "cv-api-cf"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1bmbjhkviex0y"
s3_prefix = "cv-api-stack"
region = "eu-west-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
